Iter15
ruslanjo/url_shortener pull request #15
Opened 2024-03-30 14:27 UTC by ruslanjo

2024-04-02 22:19 UTC, valentinsoe requested changes
Спасибо за работу!
Принципиальное к исправлению замечание только одно - нет асинхронного удаления URL.

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		userID := req.Header.Get(middleware.UserIDHeader)
У этой константы есть проблема - она в коде мидлвары. И получается что код хендлера зависит от кода миддлвары, что странно.
Ну и в целом общение между мидлварой и хендлерами лучше производить через контекст, а не модификацию запроса.

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		claims, err := tokenGen.GetClaims(cookie.Value)
Кажется лучше бы это проверяла мидлвара, а не конкретный хендлер.

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/middleware/auth.go
> +func generateAddAuthCookie(
Если в названии функции 2 глагола, значит она выполняет две функции:) И значит она такая себе функция:)

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/middleware/auth.go
> +			ExpiresAt: jwt.NewNumericDate(time.Now().Add(config.TokenLifeTime)),
Вот это как не странно лишнее(особенно если мы кладем токен в куку). У куки у самой есть лайфтайм.
И в данном случае мы ограничиваем пользователя "регулярно" к нам заходить, чтобы не просрочить токен в куке. То есть если он месяц не будет пользоваться сервисом, то уже сможет получить свои ссылки.

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/middleware/auth.go
> +				err = generateAddAuthCookie(&userID, tokenGen, w, r)
Написал комментарий ниже, но если кука валидна, не надо ее заменять. Пусть живет вечно:)

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/storage/db_storage.go
> +	UUID string,
Не надо называть ID пользователя - UUID, лучше назвать его userId, будет сильно понятнее:)

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/storage/hash_map_storage.go
> +	return nil, fmt.Errorf("not implemented in hashmap storage")
А почему not implemented?:)

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/storage/hash_map_storage.go
> +	return nil
Может тоже ошибку вернуть?:)

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/storage/hash_map_storage.go
>  	return nil
И тут тоже

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		err = store.DeleteURLs(context.Background(), shortURLs, userID)
Не надо создавать здесь отдельный контекст. Это не приводит к "асинхронному" удалению. Просто создается другой контекст, который не отменится, если отменится контекст запроса.

2024-04-02 22:19 UTC, valentinsoe commented on internal/app/storage/db_storage.go
> +	UUID string,
Увидел что так в тексте инкремента. Это скорее опечатка, напишу авторам курса:)

2024-04-04 19:23 UTC, ruslanjo commented on internal/app/handlers/handlers.go
> +		err = store.DeleteURLs(context.Background(), shortURLs, userID)
Исправил добавив вызов горутины

Сорри, моя ошибка что забыл вызвать функцию как горутину. 

Контекст создал не поэтому, а потому что контекст нужен для storage'a, но при этом не можем использовать контекст request'a, иначе асинхронное удаление не получится

2024-04-04 19:24 UTC, ruslanjo commented on internal/app/storage/hash_map_storage.go
> +	return nil, fmt.Errorf("not implemented in hashmap storage")
Честно - было немного лень для in-memory хранения реализовывать, оно всё равно немного вырожденное)

2024-04-04 19:25 UTC, ruslanjo commented on internal/app/storage/db_storage.go
> +	UUID string,
я здесь действительно использую UUID, поэтому так назвал. С одной стороны могу согласиться, с другой uuid тоже понятная аббревиатура для разработчика

2024-04-04 19:26 UTC, ruslanjo commented on internal/app/middleware/auth.go
> +func generateAddAuthCookie(
fixed

2024-04-04 19:27 UTC, ruslanjo commented on internal/app/handlers/handlers.go
> +		claims, err := tokenGen.GetClaims(cookie.Value)
однозначно согласен, но в ТЗ немного опять же странное требование, что хендлер себя по осбенному должен вести, можно было бы, конечно, написать отдельную  signup mw специально для этого хендлера и его сценария аутентификации

2024-04-04 19:30 UTC, ruslanjo commented on internal/app/handlers/handlers.go
> +		userID := req.Header.Get(middleware.UserIDHeader)
вынес константу в конфиг и передал значения через контекст.

Валентин, а подскажите, в языках где нет контекста, как бы вы передавали значения? У меня на работе на python была аналогичная задача, где нужно было из middleware аутентификации передавать значения в роутер, интересен ваш взгляд

2024-04-04 19:31 UTC, ruslanjo commented on cmd/shortener/main.go
> +	h "github.com/ruslanjo/url_shortener/internal/app/handlers"
Понял, буду придерживаться такого подхода. Решил сокращать из-за цепочки коллбэков mw, которая получилась довольно длинной

2024-04-04 19:32 UTC, ruslanjo commented on internal/app/storage/hash_map_storage.go
> +	return nil
done

2024-04-04 19:32 UTC, ruslanjo commented on internal/app/storage/hash_map_storage.go
>  	return nil
done

2024-04-05 23:58 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		userID := req.Header.Get(middleware.UserIDHeader)
Про python сложно сказать(я про него слишком мало знаю).
Сильно зависит от организации HTTP-библиотеки. В целом предполагаю, что библиотеки в каждом языке имеют решение для этой проблемы.

В "голом" python мне кажется логичным просто добавить к объекту запроса дополнительный атрибут в мидлваре и считать его потм в хендлере.

2024-04-05 23:59 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		claims, err := tokenGen.GetClaims(cookie.Value)
На мой взгляд это неправильная трактовка ТЗ. На мой взгляд все хендлеры лучше бы работали одинаково с авторизацией:)

2024-04-06 00:01 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		err = store.DeleteURLs(context.Background(), shortURLs, userID)
Ок. Только вопрос еще в том, что в задании была рекомендация "накапливать" в буффер задания на удаления.
Но это рекомендация, а не требование.

2024-04-06 00:02 UTC, valentinsoe approved these changes
Спасибо за исправления!

2024-04-08 08:31 UTC, merged