Iter9
ruslanjo/url_shortener pull request #9
Opened 2024-03-03 09:09 UTC by ruslanjo

2024-03-05 00:34 UTC, valentinsoe requested changes
Спасибо за работу!
В новом хендлере(JSON) лучше писать ответ в самом конце, иначе корректно ошибки вернуть не получится. Да и в целом лучше не делать заранее лишние вещи(сериализация ответа идет до попытки сохранения в хранилище).
Также не корректно сделана middleware сжатия.

2024-03-05 00:34 UTC, valentinsoe commented on cmd/shortener/main.go
> +func setUpRouter(storage storage.AbstractStorage) *chi.Mux {
Предлагаю убрать слово Abstract :) в Go  нет абстрактных классов, только интерфейсы.

2024-03-05 00:34 UTC, valentinsoe commented on cmd/shortener/main.go
> +	ds := disk.DiskStorage{Path: config.LocalStoragePath}
А почему просто не сдлать NewURLDiskStorage(config.LocalStoragePath)?

2024-03-05 00:34 UTC, valentinsoe commented on internal/app/storage/disk/disk_storage.go
> +type URLSchema struct {
В контексте URL - схема уже имеет значение(http:// или https:// - схемы). Предлагаю переименовать.

2024-03-05 19:26 UTC, ruslanjo commented on cmd/shortener/main.go
> +func setUpRouter(storage storage.AbstractStorage) *chi.Mux {
Убрал, привычка с другого языка)

2024-03-05 19:28 UTC, ruslanjo commented on cmd/shortener/main.go
> +	ds := disk.DiskStorage{Path: config.LocalStoragePath}
Хотелось бы абстрагировать URLDiskStorage от деталей реализации обращения к диску, поэтому создаю сначала просто DiskStorage, который работает непосредственно с FileSystem, а затем уже внедряю зависимость.

Наверное, действительно такая функция NewURLDiskStorage(config.LocalStoragePath), но вариает с явным DI кажется более понятным всё же

2024-03-05 19:28 UTC, ruslanjo commented on internal/app/handlers/handlers.go
> +			http.Error(w, err.Error(), http.StatusInternalServerError)
Точно, проверил, действительно в случае ошибки 201 код приходил, FIXED

2024-03-05 19:29 UTC, ruslanjo commented on internal/app/middleware/compression.go
> +		isApplicableCT := isApplicableContentType(r.Header.Get("Content-Type"))
Исправил, но что-то не очень нравится, что теперь бизнес-логика сжатия растекается по коду :(

2024-03-05 19:29 UTC, ruslanjo commented on internal/app/storage/disk/disk_storage.go
> +type URLSchema struct {
Исправил

2024-03-06 18:05 UTC, valentinsoe commented on cmd/shortener/main.go
> +	ds := disk.DiskStorage{Path: config.LocalStoragePath}
Во-первых это предварительная оптимизация, которая мало нужна.
Во-вторых если мы хотим абстрагировать, то зависеть URLDiskStorage должен от интерфейса DiskStorage, а не от конкретного типа. Иначе вс чем "абстракция" состоит?:)

2024-03-06 18:05 UTC, valentinsoe commented on internal/app/middleware/compression.go
> +		isApplicableCT := isApplicableContentType(r.Header.Get("Content-Type"))
Можно сделать, чтобы не растекалась. Просто надо придумать как:)

2024-03-16 07:57 UTC, merged